### ISSUE TITLE
AWS CloudWatch Alerts

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/aws-utils#1]
Create an alert for the different AWS services we will be using.
Let's start at a 20 USD cap per service and we will change it when we get into production

**Comment by sucksido** [comment]
Hi @GemmaTuron , I dont seem to have access to Billing and Cost Management:

![image](https://github.com/ersilia-os/aws-utils/assets/8820397/b4169e31-9617-4579-8d97-9656b9e9bad4)

We might need to add the following:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "budgets:ViewBudget",
                "budgets:CreateBudget",
                "budgets:ModifyBudget"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "SNS:Publish",
            "Resource": "*"
        }
    ]
}
`

**Comment by GemmaTuron** [comment]
seems it does not like the create budgets:
`The action budgets:CreateBudget does not exist`

**Comment by sucksido** [comment]
we can try this instead: `budgets:CreateBudgetAction`

**Comment by GemmaTuron** [comment]
done!
