### ISSUE TITLE
Create AWS account Alias name

### ISSUE THREAD

**Issue by IamEddie** [ersilia-os/aws-utils#10]

**Comment by DhanshreeA** [comment]
@IamEddie We can close this right? Can you please provide a small update here and what changed/what you did and then close this issue? Thanks Edmore! :)

**Comment by IamEddie** [comment]
Yes, @DhanshreeA. Issue is closed. We created an AWS account alias that makes it easy to login/sign in the AWS console. Instead of remembering the account number which is difficult to memories, a user only need to enter the alias name and their login credentials.
