### ISSUE TITLE
EC2 Instance for ZairaChem Model training

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/aws-utils#2]
EC2 instance to train ZairaChem models in the cloud and save resources & avoid loadshedding :)

**Comment by sucksido** [comment]
Hi @GemmaTuron , I need the following roles/policies for ec2 to able to configure SSH: `ec2-instance-connect:SendSSHPublicKey
ec2:DescribeInstances`

**Comment by sucksido** [comment]
`{
	"Version": "2012-10-17",
	"Statement": [{
			"Effect": "Allow",
			"Action": "ec2-instance-connect:SendSSHPublicKey",
			"Resource": "arn:aws:ec2:region:account-id:instance/*",
			"Condition": {
				"StringEquals": {
					"aws:ResourceTag/tag-key": "tag-value"
				}
			}
		},
		{
			"Effect": "Allow",
			"Action": "ec2:DescribeInstances",
			"Resource": "*"
		}
	]
}`

**Comment by sucksido** [comment]
![image](https://github.com/ersilia-os/aws-utils/assets/8820397/ace67fd7-bbb7-447c-b476-735f82639edb)

**Comment by GemmaTuron** [comment]
Hey @sucksido 
I get this error:
`The service ec2 does not support specifying a Region in the resource ARN`

**Comment by sucksido** [comment]
There seems to an issue with the region, we can try this: `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2-instance-connect:SendSSHPublicKey",
      "Resource": "arn:aws:ec2:instance/*",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/tag-key": "tag-value"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": "ec2:DescribeInstances",
      "Resource": "*"
    }
  ]
}
`

**Comment by sucksido** [comment]
I have successfully launched an EC2 instance to run ZairaChem. I am currently working on configurations and dependency installations, and will begin testing after all is working.

**Comment by GemmaTuron** [comment]
Should I still try the above permissions?

**Comment by GemmaTuron** [comment]
Hi @sucksido 
When you can please post an update on the status of this

**Comment by sucksido** [comment]
Update: Zairachem has been set up on an EC2 instance, I will share the log in details and the instructions privately, Now I am busy training models and encountred a Meta data issue which Jason previously raised, I am going to fix this manually today and continue testing

**Comment by sucksido** [comment]
Successfully trained model on Zairachem on our AWS ECS instance. I ran the following commands: 

`conda activate zairachem 

cd zaira-chem

zairachem fit -i /home/ec2-user/amr_small_train.csv -c 0.1 -d low -m /home/ec2-user/zairachem_models

zairachem predict -i /home/ec2-user/amr_small_test.csv -m /home/ec2-user/zairachem_models -o /home/ec2-user/zairachem_test_output`

**Comment by sucksido** [comment]
To log into the EC2 instance:

For Linux Instances:
- Use SSH to connect to your instance.
- Open your terminal or use an SSH client.
- Run the following command:
  ```sh
  ssh -i /path/to/your-key-pair.pem ec2-user@your-instance-public-dns
  ```
  Replace `/path/to/your-key-pair.pem` with the path to your key pair file and `your-instance-public-dns` with the public DNS of your instance.

**Comment by sucksido** [comment]
@JHlozek please see above comments, I have managed to train the models and run predictions, I have shared the log ins with you privately to test. Please let me know how it goes.

**Comment by GemmaTuron** [comment]
Let's see how much a fit command takes with 2000 mols - also good to know the space needed for different model sizes - how do we scale the container size automatically?
@JHlozek please pass to @sucksido some datasets for testing

**Comment by JHlozek** [comment]
Hi @sucksido, here are two expanded train/test sets from the same original Novartis_3D7 set:

[Novartis_3D7_2k_train.csv](https://github.com/user-attachments/files/15801030/Novartis_3D7_2k_train.csv)
[Novartis_3D7_2k_test.csv](https://github.com/user-attachments/files/15801031/Novartis_3D7_2k_test.csv)

**Comment by sucksido** [comment]
Thanks @JHlozek , I will train these and give feedback

**Comment by sucksido** [comment]
The training of models is still running since ~12:00 mid day today, when it's done I will run the predictions command

**Comment by GemmaTuron** [comment]
Hi @sucksido do you have the logs of the run? I find it surprising that it takes so long to train a model on 2000 molecules

**Comment by sucksido** [comment]
Hi @GemmaTuron 

Fit command ran from : 12:05 to 17:50
Predict command ran from: 20:30 - 00:51

This is all for 2000 molecules

**Comment by GemmaTuron** [comment]
mm trying to understand the costing. @JHlozek or @sucksido did you work on the EC2 Instance early in the week?
From Monday to Wednesday: 4 USD
Thursday: 0.7 USD
Does this mean 1 model costs around 1USD?

**Comment by sucksido** [comment]
@GemmaTuron i didin't do much work on it early this week but it's always running, we don't switch it off

**Comment by GemmaTuron** [comment]
But in principle, it should have a spike yesterday because you were using it? I am trying to understand baseline cost of having it on vs using it
Also, as we do not train models that often, we need to have a way of switching this on and off - how can we go about it?

**Comment by sucksido** [comment]
Agreed, we can simply turn off the instance when we are not training models and only switch it on when we need it. happy to do that.

**Comment by GemmaTuron** [comment]
@miquelduranfrigola What is the status of this?
Is this instance turned off? IF so feel free to close the issue

**Comment by miquelduranfrigola** [comment]
If I got it correctly, it should be safe to close this issue. @DhanshreeA do you have a quick way of checking if any EC2 instance is running in our AWS cloud?

**Comment by DhanshreeA** [comment]
@miquelduranfrigola and @GemmaTuron  - no instance running in our AWS - just a stopped ZairaChem instance, a persistent volume, and an elastic IP assigned to the stopped instance. The [idle elastic IP](https://aws.amazon.com/vpc/pricing/) can cost upto 3.6 USD a month (at an hourly rate of 0.005 USD) - probably best to clear these up as well.

**Comment by miquelduranfrigola** [comment]
Yes - can you do it with the current permissions?

**Comment by GemmaTuron** [comment]
All instances are stopped and/or deleted.
